_wandb:
    value:
        cli_version: 0.26.0
        e:
            wkzdumfzd4wmbglnrwc2sbnuq47poa7d:
                args:
                    - --config
                    - configs/pascal_vnode.yaml
                codePath: Mini-Project/source/scripts/run_experiment.py
                codePathLocal: scripts/run_experiment.py
                cpu_count: 2
                cpu_count_logical: 4
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "68639764480"
                        used: "33050898432"
                email: alexandre.bismuth@polytechnique.edu
                executable: /usr/bin/python
                git:
                    commit: f8a45e15fbbbbb831583679768dcfc83d30731e9
                    remote: https://github.com/alexandre-bismuth/Geometric-Deep-Learning.git
                gpu: NVIDIA A10G
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "24146608128"
                      name: NVIDIA A10G
                      uuid: GPU-0505f0ab-892f-8ac7-b395-faa29d0f1413
                host: ip-172-31-2-38.ec2.internal
                memory:
                    total: "16558182400"
                os: Linux-6.1.163-186.299.amzn2023.x86_64-x86_64-with-glibc2.34
                program: /home/ec2-user/Geometric-Deep-Learning/Mini-Project/source/scripts/run_experiment.py
                python: CPython 3.9.25
                root: /home/ec2-user/Geometric-Deep-Learning/Mini-Project/source
                startedAt: "2026-04-18T08:03:13.381497Z"
                writerId: wkzdumfzd4wmbglnrwc2sbnuq47poa7d
        m: []
        python_version: 3.9.25
        t:
            "1":
                - 1
                - 5
                - 53
                - 77
            "2":
                - 1
                - 5
                - 53
                - 77
            "3":
                - 13
                - 15
                - 16
            "4": 3.9.25
            "5": 0.26.0
            "12": 0.26.0
            "13": linux-x86_64
architecture:
    value:
        mpnn: gatedgcn
        num_layers: 4
        task: node_classification
data:
    value:
        batch_size: 32
        dataset: pascal_voc_sp
        num_workers: 4
        root: data
diagnostics:
    value:
        enabled: true
        max_graphs: 200
experiment_id:
    value: pascal-vnode
logging:
    value:
        save_dir: outputs
        wandb_project: graph-transformer-sinks
model:
    value:
        attn_dropout: 0.5
        dropout: 0
        hidden_dim: 96
        num_heads: 8
pe:
    value:
        dim: 16
        type: lappe
training:
    value:
        epochs: 300
        grad_clip: 1
        lr: 0.0005
        warmup_epochs: 10
        weight_decay: 0
vnode:
    value:
        enabled: true
        num_edge_types: 5
        num_node_types: 29
        vnode_edge_type: 4
        vnode_node_type: 28
