"""Generate manifests/camera_ready_q1.txt (GDDL camera-ready, GPU Job 1).

ONE NODE ONLY (4 GPUs). Order = priority: workers claim the first claimable line top-down,
so whatever finishes before the camera-ready deadline is the most important part.
Analysis lines of a run that is still training are released automatically by the
not-ready guard in slurm/worker_pool.sh and retried later.
"""
import sys

L = []
P = lambda *a: L.extend(a)


def post_zinc(run):
    return [f'eval outputs/{run} full trained', f'ablate outputs/{run}', f'ablatenr outputs/{run}',
            f'cert outputs/{run}', f'probe outputs/{run}', f'perturb outputs/{run}']


def post_pep(run):
    return [f'eval outputs/{run} full trained']


def block(runner, cfg, exp, seeds, post=post_zinc):
    out = [f'train {runner} configs/{cfg}.yaml {s}' for s in seeds]
    for s in seeds:
        out += post(f'{exp}-s{s}')
    return out


P('# GDDL 2026 camera-ready, GPU Job 1 (one node). Generated by scripts/gen_camera_ready_queue.py; order = priority.',
  '# P0: Peptides re-evaluation with the new diagnostics (writes *_cr files; never overwrites).')
P(*[f'reeval outputs/peptides-grit-s{s}' for s in (0, 1, 2)])
P('# P1 (BLOCKING): single-factor swap (only the logit becomes q.k) and the structure-blind GRIT control.')
P(*block('grit', 'zinc_grit_dotlogit', 'zinc-grit-dotlogit', (0, 1, 2)))
P(*block('grit', 'zinc_grit_blind', 'zinc-grit-blind', (0, 1, 2)))
P('# P1b (BLOCKING): GraphGPS seeds 3,4. With seeded runs only (n=3), GraphGPS [0.11, 0.62] overlaps',
  '#   GRIT [0.06, 0.12]; n=5 restores the headline contrast. (~8 h each; fills idle workers.)')
P(*block('gps', 'zinc_graphgps', 'zinc-graphgps', (3, 4)))
P('# P2 (BLOCKING): is the clamp causal? retrain without it / with the official GRIT ordering.')
P(*block('grit', 'zinc_grit_noclamp', 'zinc-grit-noclamp', (0, 1, 2)))
P(*block('grit', 'zinc_grit_official', 'zinc-grit-official', (0, 1, 2)))
P('# P3: single-factor swap on Peptides (size trend inside one model).')
P(*block('grit', 'peptides_grit_dotlogit', 'peptides-grit-dotlogit', (0, 1, 2), post_pep))
P('# P4: seeds 3,4 for GRIT and GRIT+VN (n=5).')
for runner, cfg, exp in [('grit', 'zinc_grit', 'zinc-grit'), ('grit', 'zinc_grit_vnode', 'zinc-grit-vnode')]:
    P(*block(runner, cfg, exp, (3, 4)))
P('# P5: depth 20, one seed per arm (~2x a 10-layer run; resumes across walltime from ckpt.pt).')
P(*block('grit', 'zinc_grit_L20', 'zinc-grit-L20', (0,)))
P(*block('grit', 'zinc_grit_dotlogit_L20', 'zinc-grit-dotlogit-L20', (0,)))
P('# P6: gated logit + dot term.')
P(*block('grit', 'zinc_grit_plusdot', 'zinc-grit-plusdot', (0, 1, 2)))
P('# P7: depth 20, seeds 1,2.')
P(*block('grit', 'zinc_grit_L20', 'zinc-grit-L20', (1, 2)))
P(*block('grit', 'zinc_grit_dotlogit_L20', 'zinc-grit-dotlogit-L20', (1, 2)))
P('# P8 (optional; unlikely to be reached on one node): seeds 3,4 for the remaining ZINC arms.')
for runner, cfg, exp in [('grit', 'zinc_grit_dot', 'zinc-grit-dot'), ('grit', 'zinc_grit_dotbias', 'zinc-grit-dotbias'),
                         ('gps', 'zinc_gps_none', 'zinc-gps-none'), ('gps', 'zinc_gps_vnode', 'zinc-gps-vnode'),
                         ('gps', 'zinc_gps_gatedgcn', 'zinc-gps-gatedgcn'),
                         ('gps', 'zinc_gps_lappe_none', 'zinc-gps-lappe-none'),
                         ('gps', 'zinc_gps_vnode_perecomp', 'zinc-gps-vnode-perecomp'),
                         ('grit', 'zinc_grit_vnode_bias', 'zinc-grit-vnode-bias'),
                         ('grit', 'zinc_grit_vnode_perecomp', 'zinc-grit-vnode-perecomp'),
                         ('grit', 'zinc_grit_forced_ent1', 'zinc-grit-forced-ent1'),
                         ('grit', 'zinc_grit_forced_ent2', 'zinc-grit-forced-ent2')]:
    P(*block(runner, cfg, exp, (3, 4)))

assert len(set(l for l in L if not l.startswith('#'))) == len([l for l in L if not l.startswith('#')]), 'duplicate line'
open(sys.argv[1], 'w').write('\n'.join(L) + '\n')
# ZINC-only variant for the first jobs: same lines (same md5 state keys), Peptides removed, so
# no job waits on the ~25 GB Peptides cache before its GPUs start (build it in the background
# with BG_CACHE_CONFIGS=configs/peptides_grit.yaml, then switch to the full queue).
zinc = [l for l in L if 'peptides' not in l]
open(sys.argv[1].replace('.txt', '_zinc.txt'), 'w').write('\n'.join(zinc) + '\n')
tr = [l for l in L if l.startswith('train')]
print(len(tr), 'train lines;', sum(1 for l in L if l and not l.startswith(('#', 'train'))), 'analysis lines')
